### ISSUE TITLE
Random HTTP(S) connection issues with Android builds

### ISSUE THREAD

**Issue by rh101** [adxeproject/adxe#443] opened 2021-08-04 03:39 UTC
- adxe version: dev branch, https://github.com/adxeproject/adxe/tree/cfffd35aeca3b03216f9845e14b3eafc6340ef74
- devices test on: Emulator x86 Android 9.0, and sometimes on 10.0 & 11.0
- developing environments
   - NDK version: 21.3.6528147 & 22.1.7171670
   - Xcode version:
   - VS/msvctools version: Visual Studio 2019/14.28.29910
   - cmake version: 3.10.2

```
2021-08-04 13:21:33.925 3643-5038/com.app.my I/yasio: [yasio][1628047293925][index: 4] connecting server [REMOTE_DNS](REMOTE_IP):6901...
2021-08-04 13:21:33.967 3643-5038/com.app.my I/yasio: [yasio][1628047293967][index: 4] the connection #49(0xc922f030) [LOCAL_IP:YYYY] --> [EXTERNAL_IP:ZZZZ] is established.
2021-08-04 13:21:33.975 3643-5038/com.app.my I/yasio: [yasio][1628047293975][index: 4] the connection #49(0xc922f030) is lost, ec=-20, where=1, detail:End of file.
2021-08-04 13:21:34.008 3643-5030/com.app.my D/cocos2d-x debug info: Error -1 in request
```

It's returning `the connection #49(0xc922f030) is lost, ec=-20, where=1, detail:End of file.` on random HTTPS requests.

On the server I can see the response being sent back as 200 (OK), so it's something on the client that is causing this problem.

I haven't experienced this issue with Win32 builds. It's happening just on Android so far. 

Any hints as to why this is happening, or something I can do to log everything going on in yasio?

**Comment by halx99** [comment] 2021-08-04 06:15
ec=-20, where=1 usually caused by server close the socket

**Comment by halx99** [comment] 2021-08-04 06:36
Can you provide a reporduce test project, and test server url?

**Comment by rh101** [comment] 2021-08-04 06:37
Already working on creating one :)

**Comment by rh101** [comment] 2021-08-04 08:05
@halx99 Do you have a private email address I can use to send the test case to you? The project uses a private IP address for the server, so I can't post it here.  Alternatively I can send you the IP address via email, and upload the test case in here (without the `cocos2d` folder, since you can just use the one you have).

**Comment by halx99** [comment] 2021-08-04 08:06
Just send to halx99 at live dot com

**Comment by rh101** [comment] 2021-08-04 08:12
I just sent it to your email. Extract the archive into a folder named "testapp", add the cocos2d folder to it, and it should be good to go.  I tested it on Win32, and no problem at all, but when using Android emulators, the same issue appears.

**Comment by halx99** [comment] 2021-08-04 08:33
Got it, I will test it later, by the way, Can I use real android device to test it?

**Comment by halx99** [comment] 2021-08-04 09:46
ok, I will test on x86 emulator

**Comment by halx99** [comment] 2021-08-04 10:30
I have test many times, it seems works well on android x86 enumlator (android 11):
![image](https://user-images.githubusercontent.com/6977319/128166345-9cd52009-e591-431e-a3d3-87e35e28cf22.png)

**Comment by halx99** [comment] 2021-08-04 10:30
I have test many times, it's seems works well on android x86 emulators(android 11)

**Comment by halx99** [comment] 2021-08-04 10:35
And notes, your code use unique_ptr manage request, that is incorrect

**Comment by halx99** [comment] 2021-08-04 10:39
![image](https://user-images.githubusercontent.com/6977319/128167524-adc43dab-425f-450b-9962-e87a7701ddfa.png)

**Comment by rh101** [comment] 2021-08-04 10:42
> 
> 
> And notes, your code use unique_ptr manage request, that is incorrect, it damage reference count management of HttpRequest by HttpClient

Oh yes sorry, that was just a quick bit of code. I'm re-testing it right now to get the output so I can paste it here.

**Comment by rh101** [comment] 2021-08-04 10:47
This is what I'm seeing:

```
2021-08-04 20:46:42.440 16694-16769/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
2021-08-04 20:46:49.339 16694-16769/com.example.testapp D/cocos2d-x debug info: >>> Error -1 in request
2021-08-04 20:46:50.227 16694-16769/com.example.testapp D/cocos2d-x debug info: >>> Error -1 in request
2021-08-04 20:46:51.199 16694-16769/com.example.testapp D/cocos2d-x debug info: >>> Error -1 in request
2021-08-04 20:46:52.155 16694-16769/com.example.testapp D/cocos2d-x debug info: >>> Error -1 in request
2021-08-04 20:46:53.059 16694-16769/com.example.testapp D/cocos2d-x debug info: >>> Error -1 in request
2021-08-04 20:46:53.789 16694-16769/com.example.testapp D/cocos2d-x debug info: >>> Error -1 in request
2021-08-04 20:46:54.415 16694-16769/com.example.testapp D/cocos2d-x debug info: >>> Error -1 in request
2021-08-04 20:46:55.875 16694-16769/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
2021-08-04 20:46:56.987 16694-16769/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
2021-08-04 20:46:57.857 16694-16769/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
2021-08-04 20:46:58.987 16694-16769/com.example.testapp D/cocos2d-x debug info: >>> Error -1 in request
2021-08-04 20:46:59.821 16694-16769/com.example.testapp D/cocos2d-x debug info: >>> Error -1 in request
2021-08-04 20:47:01.489 16694-16769/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
2021-08-04 20:47:02.966 16694-16769/com.example.testapp D/cocos2d-x debug info: >>> Error -1 in request
```

**Comment by halx99** [comment] 2021-08-04 10:50
So I needs install androd 9 to test? Yes, it maybe your network issue, you can try use wireshark to capture TCP internal RST signal

**Comment by rh101** [comment] 2021-08-04 10:58
I'm getting it on all versions of Android, so I'll use Wireshark to check the network traffic. Ignore this issue for the time being until I find out more.

**Comment by rh101** [comment] 2021-08-04 13:38
Wireshark isn't showing me anything out of the ordinary.  As you can see here, the top two request/responses (marked in red) are giving me an `error = -1` from yasio, while the last request/response producing no error:

![image](https://user-images.githubusercontent.com/8603230/128190684-feddb1d4-2001-435a-a11b-4e59ea5cbddf.png)

This is really strange.

**Comment by rh101** [comment] 2021-08-04 13:59
Testing with the Android 11 x86 emulator, I only managed to get the error once out of around 60+ attempts, and for Android 10 x86 emulator, it didn't happen at all with this test app, so perhaps it does have something to do with Android 9.0:
![image](https://user-images.githubusercontent.com/8603230/128193485-a48cb804-9cf8-4dc5-9409-10e5b969a44d.png)

**Comment by halx99** [comment] 2021-08-04 14:15
Yes, I use android 9 emulator, it reproduced, and the follow is wireshark report:
![image](https://user-images.githubusercontent.com/6977319/128196861-6d682324-2bf8-459f-a113-fa7ef2258917.png)
You can see, server close the socket without any response.

**Comment by halx99** [comment] 2021-08-04 14:19
And also reproduce the issue same wireshark capture result without, everythings looks well, it's so strange

**Comment by halx99** [comment] 2021-08-04 14:22
Maybe caused by network driver implement bug on android emulator 9.0, you can see the connection lost check at: 
https://github.com/yasio/yasio/blob/main/yasio/yasio.cpp#L449

When the lowlevel non-blocking socket recv return zero, that means the connection closed by peer

**Comment by rh101** [comment] 2021-08-04 14:27
> When the lowlevel non-blocking socket recv return zero, that means the connection closed by peer

Does that mean it's an issue specific to emulators and I shouldn't worry about it?

**Comment by halx99** [comment] 2021-08-04 14:29
I think so, and maybe we can test other netowrk framework on android 9.0 emulator to comfirm it, such as `curl` or `beast`

**Comment by rh101** [comment] 2021-08-04 14:33
> 
> 
> I think so, and maybe we can test other netowrk framework on android 9.0 emulator to comfirm it, such as `curl` or `beast`

Do you have any snippet of code I can use to test out curl? Otherwise, I'll try to create a curl test sometime later today.

**Comment by halx99** [comment] 2021-08-04 14:39
I don't have yet.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by rh101** [comment] 2021-08-04 15:23
> I don't have yet.

I've emailed you the curl test code.  The curl request worked correctly 100% of the time in the Android 9.0 emulator, if that helps in some way.

**Comment by halx99** [comment] 2021-08-04 16:36
Thanks, I will check it

**Comment by halx99** [comment] 2021-08-05 04:16
Can you change your server to reply some data when use POST method to request, or do I needs fill some parameter in the reuqest json data?

**Comment by rh101** [comment] 2021-08-05 04:28
I'll update the server now and let you know when it's ready.

**Comment by rh101** [comment] 2021-08-05 05:32
@halx99 The server should now return a JSON result in the body of the response for the same endpoint.

**Comment by halx99** [comment] 2021-08-05 06:31
I have test curl, and I dump response hex in curl socket recv function: curl/lib/sendf.c,  it also have the same issue, you can see the output log, complete response data size should be 210 bytes, but the second one, only 209 bytes, and the curl report responseCode 200 always even though the response data incomplete:

## curl http request
```txt
2021-08-05 14:18:11.539 13540-13571/com.example.testapp D/curl debug info: data.len=210, non-blocking: true, hex is:
2021-08-05 14:18:11.540 13540-13571/com.example.testapp D/curl debug info: 0x48,0x54,0x54,0x50,0x2f,0x31,0x2e,0x31,0x20,0x32,0x30,0x30,0x20,0x4f,0x4b,0x0d,
2021-08-05 14:18:11.540 13540-13571/com.example.testapp D/curl debug info: 0x0a,0x43,0x6f,0x6e,0x6e,0x65,0x63,0x74,0x69,0x6f,0x6e,0x3a,0x20,0x63,0x6c,0x6f,
2021-08-05 14:18:11.540 13540-13571/com.example.testapp D/curl debug info: 0x73,0x65,0x0d,0x0a,0x44,0x61,0x74,0x65,0x3a,0x20,0x54,0x68,0x75,0x2c,0x20,0x30,
2021-08-05 14:18:11.540 13540-13571/com.example.testapp D/curl debug info: 0x35,0x20,0x41,0x75,0x67,0x20,0x32,0x30,0x32,0x31,0x20,0x30,0x36,0x3a,0x31,0x38,
2021-08-05 14:18:11.540 13540-13571/com.example.testapp D/curl debug info: 0x3a,0x31,0x30,0x20,0x47,0x4d,0x54,0x0d,0x0a,0x43,0x6f,0x6e,0x74,0x65,0x6e,0x74,
2021-08-05 14:18:11.540 13540-13571/com.example.testapp D/curl debug info: 0x2d,0x54,0x79,0x70,0x65,0x3a,0x20,0x61,0x70,0x70,0x6c,0x69,0x63,0x61,0x74,0x69,
2021-08-05 14:18:11.540 13540-13571/com.example.testapp D/curl debug info: 0x6f,0x6e,0x2f,0x6a,0x73,0x6f,0x6e,0x3b,0x20,0x63,0x68,0x61,0x72,0x73,0x65,0x74,
2021-08-05 14:18:11.540 13540-13571/com.example.testapp D/curl debug info: 0x3d,0x75,0x74,0x66,0x2d,0x38,0x0d,0x0a,0x53,0x65,0x72,0x76,0x65,0x72,0x3a,0x20,
2021-08-05 14:18:11.540 13540-13571/com.example.testapp D/curl debug info: 0x4b,0x65,0x73,0x74,0x72,0x65,0x6c,0x0d,0x0a,0x54,0x72,0x61,0x6e,0x73,0x66,0x65,
2021-08-05 14:18:11.540 13540-13571/com.example.testapp D/curl debug info: 0x72,0x2d,0x45,0x6e,0x63,0x6f,0x64,0x69,0x6e,0x67,0x3a,0x20,0x63,0x68,0x75,0x6e,
2021-08-05 14:18:11.540 13540-13571/com.example.testapp D/curl debug info: 0x6b,0x65,0x64,0x0d,0x0a,0x0d,0x0a,0x32,0x30,0x0d,0x0a,0x7b,0x22,0x69,0x64,0x22,
2021-08-05 14:18:11.540 13540-13571/com.example.testapp D/curl debug info: 0x3a,0x22,0x49,0x44,0x35,0x33,0x32,0x22,0x2c,0x22,0x74,0x65,0x73,0x74,0x56,0x61,
2021-08-05 14:18:11.540 13540-13571/com.example.testapp D/curl debug info: 0x6c,0x75,0x65,0x22,0x3a,0x33,0x33,0x30,0x34,0x38,0x7d,0x0d,0x0a,0x30,0x0d,0x0a,
2021-08-05 14:18:11.540 13540-13571/com.example.testapp D/curl debug info: 0x0d,0x0a,
2021-08-05 14:18:11.541 13540-13571/com.example.testapp D/cocos2d-x debug info: >>> CURL RESPONSE 200 OK
2021-08-05 14:18:23.261 13540-13571/com.example.testapp D/curl debug info: data.len=209, non-blocking: true, hex is:
2021-08-05 14:18:23.261 13540-13571/com.example.testapp D/curl debug info: 0x48,0x54,0x54,0x50,0x2f,0x31,0x2e,0x31,0x20,0x32,0x30,0x30,0x20,0x4f,0x4b,0x0d,
2021-08-05 14:18:23.261 13540-13571/com.example.testapp D/curl debug info: 0x0a,0x43,0x6f,0x6e,0x6e,0x65,0x63,0x74,0x69,0x6f,0x6e,0x3a,0x20,0x63,0x6c,0x6f,
2021-08-05 14:18:23.261 13540-13571/com.example.testapp D/curl debug info: 0x73,0x65,0x0d,0x0a,0x44,0x61,0x74,0x65,0x3a,0x20,0x54,0x68,0x75,0x2c,0x20,0x30,
2021-08-05 14:18:23.261 13540-13571/com.example.testapp D/curl debug info: 0x35,0x20,0x41,0x75,0x67,0x20,0x32,0x30,0x32,0x31,0x20,0x30,0x36,0x3a,0x31,0x38,
2021-08-05 14:18:23.261 13540-13571/com.example.testapp D/curl debug info: 0x3a,0x32,0x32,0x20,0x47,0x4d,0x54,0x0d,0x0a,0x43,0x6f,0x6e,0x74,0x65,0x6e,0x74,
2021-08-05 14:18:23.261 13540-13571/com.example.testapp D/curl debug info: 0x2d,0x54,0x79,0x70,0x65,0x3a,0x20,0x61,0x70,0x70,0x6c,0x69,0x63,0x61,0x74,0x69,
2021-08-05 14:18:23.261 13540-13571/com.example.testapp D/curl debug info: 0x6f,0x6e,0x2f,0x6a,0x73,0x6f,0x6e,0x3b,0x20,0x63,0x68,0x61,0x72,0x73,0x65,0x74,
2021-08-05 14:18:23.261 13540-13571/com.example.testapp D/curl debug info: 0x3d,0x75,0x74,0x66,0x2d,0x38,0x0d,0x0a,0x53,0x65,0x72,0x76,0x65,0x72,0x3a,0x20,
2021-08-05 14:18:23.261 13540-13571/com.example.testapp D/curl debug info: 0x4b,0x65,0x73,0x74,0x72,0x65,0x6c,0x0d,0x0a,0x54,0x72,0x61,0x6e,0x73,0x66,0x65,
2021-08-05 14:18:23.261 13540-13571/com.example.testapp D/curl debug info: 0x72,0x2d,0x45,0x6e,0x63,0x6f,0x64,0x69,0x6e,0x67,0x3a,0x20,0x63,0x68,0x75,0x6e,
2021-08-05 14:18:23.261 13540-13571/com.example.testapp D/curl debug info: 0x6b,0x65,0x64,0x0d,0x0a,0x0d,0x0a,0x32,0x30,0x0d,0x0a,0x7b,0x22,0x69,0x64,0x22,
2021-08-05 14:18:23.261 13540-13571/com.example.testapp D/curl debug info: 0x3a,0x22,0x49,0x44,0x35,0x33,0x32,0x22,0x2c,0x22,0x74,0x65,0x73,0x74,0x56,0x61,
2021-08-05 14:18:23.261 13540-13571/com.example.testapp D/curl debug info: 0x6c,0x75,0x65,0x22,0x3a,0x33,0x33,0x30,0x34,0x38,0x7d,0x0d,0x0a,0x30,0x0d,0x0a,
2021-08-05 14:18:23.261 13540-13571/com.example.testapp D/curl debug info: 0x0d,
2021-08-05 14:18:23.261 13540-13571/com.example.testapp D/curl debug info: recv return 0, should clos
2021-08-05 14:18:23.262 13540-13571/com.example.testapp D/cocos2d-x debug info: >>> CURL RESPONSE 200 OK
```
[sendf.zip](https://github.com/adxeproject/adxe/files/6936393/sendf.zip)

## yasio http request:
```txt
2021-08-05 14:21:53.367 13696-13747/com.example.testapp D/yasio debug info: data.len=210, non-blocking: true, hex is:
2021-08-05 14:21:53.367 13696-13747/com.example.testapp D/curl debug info: 0x48,0x54,0x54,0x50,0x2f,0x31,0x2e,0x31,0x20,0x32,0x30,0x30,0x20,0x4f,0x4b,0x0d,
2021-08-05 14:21:53.367 13696-13747/com.example.testapp D/curl debug info: 0x0a,0x43,0x6f,0x6e,0x6e,0x65,0x63,0x74,0x69,0x6f,0x6e,0x3a,0x20,0x63,0x6c,0x6f,
2021-08-05 14:21:53.368 13696-13747/com.example.testapp D/curl debug info: 0x73,0x65,0x0d,0x0a,0x44,0x61,0x74,0x65,0x3a,0x20,0x54,0x68,0x75,0x2c,0x20,0x30,
2021-08-05 14:21:53.368 13696-13747/com.example.testapp D/curl debug info: 0x35,0x20,0x41,0x75,0x67,0x20,0x32,0x30,0x32,0x31,0x20,0x30,0x36,0x3a,0x32,0x31,
2021-08-05 14:21:53.368 13696-13747/com.example.testapp D/curl debug info: 0x3a,0x35,0x32,0x20,0x47,0x4d,0x54,0x0d,0x0a,0x43,0x6f,0x6e,0x74,0x65,0x6e,0x74,
2021-08-05 14:21:53.368 13696-13747/com.example.testapp D/curl debug info: 0x2d,0x54,0x79,0x70,0x65,0x3a,0x20,0x61,0x70,0x70,0x6c,0x69,0x63,0x61,0x74,0x69,
2021-08-05 14:21:53.368 13696-13747/com.example.testapp D/curl debug info: 0x6f,0x6e,0x2f,0x6a,0x73,0x6f,0x6e,0x3b,0x20,0x63,0x68,0x61,0x72,0x73,0x65,0x74,
2021-08-05 14:21:53.368 13696-13747/com.example.testapp D/curl debug info: 0x3d,0x75,0x74,0x66,0x2d,0x38,0x0d,0x0a,0x53,0x65,0x72,0x76,0x65,0x72,0x3a,0x20,
2021-08-05 14:21:53.368 13696-13747/com.example.testapp D/curl debug info: 0x4b,0x65,0x73,0x74,0x72,0x65,0x6c,0x0d,0x0a,0x54,0x72,0x61,0x6e,0x73,0x66,0x65,
2021-08-05 14:21:53.368 13696-13747/com.example.testapp D/curl debug info: 0x72,0x2d,0x45,0x6e,0x63,0x6f,0x64,0x69,0x6e,0x67,0x3a,0x20,0x63,0x68,0x75,0x6e,
2021-08-05 14:21:53.368 13696-13747/com.example.testapp D/curl debug info: 0x6b,0x65,0x64,0x0d,0x0a,0x0d,0x0a,0x32,0x30,0x0d,0x0a,0x7b,0x22,0x69,0x64,0x22,
2021-08-05 14:21:53.368 13696-13747/com.example.testapp D/curl debug info: 0x3a,0x22,0x49,0x44,0x35,0x33,0x32,0x22,0x2c,0x22,0x74,0x65,0x73,0x74,0x56,0x61,
2021-08-05 14:21:53.368 13696-13747/com.example.testapp D/curl debug info: 0x6c,0x75,0x65,0x22,0x3a,0x33,0x33,0x30,0x34,0x38,0x7d,0x0d,0x0a,0x30,0x0d,0x0a,
2021-08-05 14:21:53.368 13696-13747/com.example.testapp D/curl debug info: 0x0d,0x0a,
2021-08-05 14:21:53.368 13696-13747/com.example.testapp D/cocos2d-x debug info: <<<READ data: HTTP/1.1 200 OK
    Connection: close
    Date: Thu, 05 Aug 2021 06:21:52 GMT
    Content-Type: application/json; charset=utf-8
    Server: Kestrel
    Transfer-Encoding: chunked
    
    20
    {"id":"ID532","testValue":33048}
    0
    
    >>>
2021-08-05 14:21:53.369 13696-13747/com.example.testapp I/yasio: [yasio][1628144513369][index: 0] the connection #26(0xc9957e80) is lost, ec=-20, where=1, detail:End of file.

2021-08-05 14:21:57.533 13696-13747/com.example.testapp D/yasio debug info: data.len=209, non-blocking: true, hex is:
2021-08-05 14:21:57.533 13696-13747/com.example.testapp D/curl debug info: 0x48,0x54,0x54,0x50,0x2f,0x31,0x2e,0x31,0x20,0x32,0x30,0x30,0x20,0x4f,0x4b,0x0d,
2021-08-05 14:21:57.533 13696-13747/com.example.testapp D/curl debug info: 0x0a,0x43,0x6f,0x6e,0x6e,0x65,0x63,0x74,0x69,0x6f,0x6e,0x3a,0x20,0x63,0x6c,0x6f,
2021-08-05 14:21:57.533 13696-13747/com.example.testapp D/curl debug info: 0x73,0x65,0x0d,0x0a,0x44,0x61,0x74,0x65,0x3a,0x20,0x54,0x68,0x75,0x2c,0x20,0x30,
2021-08-05 14:21:57.533 13696-13747/com.example.testapp D/curl debug info: 0x35,0x20,0x41,0x75,0x67,0x20,0x32,0x30,0x32,0x31,0x20,0x30,0x36,0x3a,0x32,0x31,
2021-08-05 14:21:57.533 13696-13747/com.example.testapp D/curl debug info: 0x3a,0x35,0x36,0x20,0x47,0x4d,0x54,0x0d,0x0a,0x43,0x6f,0x6e,0x74,0x65,0x6e,0x74,
2021-08-05 14:21:57.533 13696-13747/com.example.testapp D/curl debug info: 0x2d,0x54,0x79,0x70,0x65,0x3a,0x20,0x61,0x70,0x70,0x6c,0x69,0x63,0x61,0x74,0x69,
2021-08-05 14:21:57.533 13696-13747/com.example.testapp D/curl debug info: 0x6f,0x6e,0x2f,0x6a,0x73,0x6f,0x6e,0x3b,0x20,0x63,0x68,0x61,0x72,0x73,0x65,0x74,
2021-08-05 14:21:57.533 13696-13747/com.example.testapp D/curl debug info: 0x3d,0x75,0x74,0x66,0x2d,0x38,0x0d,0x0a,0x53,0x65,0x72,0x76,0x65,0x72,0x3a,0x20,
2021-08-05 14:21:57.533 13696-13747/com.example.testapp D/curl debug info: 0x4b,0x65,0x73,0x74,0x72,0x65,0x6c,0x0d,0x0a,0x54,0x72,0x61,0x6e,0x73,0x66,0x65,
2021-08-05 14:21:57.533 13696-13747/com.example.testapp D/curl debug info: 0x72,0x2d,0x45,0x6e,0x63,0x6f,0x64,0x69,0x6e,0x67,0x3a,0x20,0x63,0x68,0x75,0x6e,
2021-08-05 14:21:57.533 13696-13747/com.example.testapp D/curl debug info: 0x6b,0x65,0x64,0x0d,0x0a,0x0d,0x0a,0x32,0x30,0x0d,0x0a,0x7b,0x22,0x69,0x64,0x22,
2021-08-05 14:21:57.533 13696-13747/com.example.testapp D/curl debug info: 0x3a,0x22,0x49,0x44,0x35,0x33,0x32,0x22,0x2c,0x22,0x74,0x65,0x73,0x74,0x56,0x61,
2021-08-05 14:21:57.533 13696-13747/com.example.testapp D/curl debug info: 0x6c,0x75,0x65,0x22,0x3a,0x33,0x33,0x30,0x34,0x38,0x7d,0x0d,0x0a,0x30,0x0d,0x0a,
2021-08-05 14:21:57.533 13696-13747/com.example.testapp D/curl debug info: 0x0d,
2021-08-05 14:21:57.533 13696-13747/com.example.testapp D/cocos2d-x debug info: <<<READ data: HTTP/1.1 200 OK
    Connection: close
    Date: Thu, 05 Aug 2021 06:21:56 GMT
    Content-Type: application/json; charset=utf-8
    Server: Kestrel
    Transfer-Encoding: chunked
    
    20
    {"id":"ID532","testValue":33048}
    0
    >>>
2021-08-05 14:21:57.533 13696-13747/com.example.testapp I/yasio: [yasio][1628144517533][index: 0] the connection #27(0xc9957e80) is lost, ec=-20, where=1, detail:End of file.
2021-08-05 14:21:57.539 13696-13726/com.example.testapp D/cocos2d-x debug info: >>> Error -1 in request, internalCode: -20
```

## Note:
- By default, the curl not header: "Connection: Close"
- I add the header "Connection: Close" to test, this issue could be easy repreduce with curl request

**Comment by rh101** [comment] 2021-08-05 06:38
This is so strange.  I've been checking if it's an issue with Kestrel server, because there is nothing special that is being done by the .Net Core code to return the response.  Thank you for taking time to look into this. I'll try to see what is going on here with the responses.

**Comment by halx99** [comment] 2021-08-05 06:46
I also remove  "Connection: Close" from yasio http client, and test many times, 100% works:

```txt
Line 34: 2021-08-05 14:34:47.482 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 63: 2021-08-05 14:34:53.618 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 92: 2021-08-05 14:34:57.137 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 124: 2021-08-05 14:34:59.701 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 153: 2021-08-05 14:35:01.486 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 185: 2021-08-05 14:35:04.741 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 217: 2021-08-05 14:35:08.632 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 249: 2021-08-05 14:35:12.160 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 278: 2021-08-05 14:35:14.821 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 307: 2021-08-05 14:35:16.712 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 336: 2021-08-05 14:35:18.538 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 365: 2021-08-05 14:35:20.354 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 394: 2021-08-05 14:35:22.214 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 423: 2021-08-05 14:35:23.777 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 452: 2021-08-05 14:35:26.262 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 481: 2021-08-05 14:35:27.823 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 510: 2021-08-05 14:35:29.444 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 539: 2021-08-05 14:35:31.001 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 568: 2021-08-05 14:35:32.486 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 597: 2021-08-05 14:35:33.977 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 626: 2021-08-05 14:35:35.493 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 655: 2021-08-05 14:35:37.408 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 684: 2021-08-05 14:35:38.965 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 716: 2021-08-05 14:35:41.930 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 745: 2021-08-05 14:35:43.027 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 774: 2021-08-05 14:35:45.241 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 803: 2021-08-05 14:35:49.842 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 832: 2021-08-05 14:35:51.816 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 861: 2021-08-05 14:35:53.566 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 890: 2021-08-05 14:35:56.013 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 919: 2021-08-05 14:35:57.793 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 948: 2021-08-05 14:35:59.793 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 980: 2021-08-05 14:36:02.498 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 1009: 2021-08-05 14:36:04.513 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 1038: 2021-08-05 14:36:07.823 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 1067: 2021-08-05 14:36:11.128 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 1099: 2021-08-05 14:36:15.053 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 1128: 2021-08-05 14:36:19.138 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 1157: 2021-08-05 14:36:21.119 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 1186: 2021-08-05 14:36:22.763 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 1215: 2021-08-05 14:36:25.417 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 1244: 2021-08-05 14:36:28.334 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 1273: 2021-08-05 14:36:29.908 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
	Line 1302: 2021-08-05 14:36:31.448 14001-14030/com.example.testapp D/cocos2d-x debug info: >>> RESPONSE RECEIVED (200)
```

**Comment by halx99** [comment] 2021-08-05 06:57
The latest commit can solve this issue.

**Closed** 2021-08-05 06:56 UTC

**Comment by rh101** [comment] 2021-08-05 06:58
Excellent, and thank you very much for your help with this!

**Comment by halx99** [comment] 2021-08-05 07:04
You are welcome, and thanks for you report this issue at here, it very useful for improve our HttpClient robustness.
